/* Local, offline-first interaction prototype. No model calls, recording, or remote scoring. */
'use strict';
const KEY = 'ais-campus-demo-v2';
const initial = () => ({reading: {}, drafts: {}, followups: {}, reviewed: {}, friendDone: false, friendChoice: 0, friendReply: '', warmup: false});
let state = initial();
try { const saved = JSON.parse(localStorage.getItem(KEY)); if (saved && typeof saved === 'object' && !Array.isArray(saved)) state = {...state, ...saved}; } catch (_) {}
for (const key of ['reading','drafts','followups','reviewed']) if (!state[key] || typeof state[key] !== 'object' || Array.isArray(state[key])) state[key] = {};
const main = document.querySelector('#main');
const sources = {
  ets: 'https://www.ets.org/pdfs/toefl/toefl-ibt-reading-practice-sets.pdf#page=8',
  google: 'https://grow.google/grow-your-career/articles/interview-tips/',
  amazon: 'https://www.amazon.jobs/content/en/our-workplace/leadership-principles',
  star: 'https://amazon.jobs/content/en/how-we-hire/interview-loop'
};
const questions = {
  google: [
    {title: 'A difficult decision', tag: 'Decision-making', prompt: 'Tell me about a difficult decision you made with incomplete information. How did you choose what to do?', follow: 'Which assumption mattered most, and how did you test it?', hint: 'I weighed … against … before deciding to …', sample: 'In a student project, our survey had only twelve responses. I was responsible for choosing the first feature. I compared the survey with five short interviews and proposed a small scheduling prototype instead of a full app. Four testers completed the task without help. I learned to test a decision before expanding its scope.'},
    {title: 'An unexpected problem', tag: 'Problem-solving', prompt: 'Describe a challenging technical problem you helped solve. What did you personally do?', follow: 'How did you distinguish the root cause from a symptom?', hint: 'To isolate the cause, I first … Then I …', sample: 'Our club website stopped accepting registrations before an event. I owned the sign-up form. I reproduced the failure, checked the requests, and found a validation mismatch. I corrected the rule and added a regression test. Registration reopened that afternoon. I learned to test realistic inputs before a release.'},
    {title: 'Make your impact clear', tag: 'Evidence & reflection', prompt: 'Tell me about a project where your contribution made a measurable difference. How did you establish the result?', follow: 'What else could have influenced the outcome?', hint: 'My contribution was … We measured it by …', sample: 'Our reading group struggled to finish weekly sessions. I coordinated the schedule. I introduced a shared agenda and limited each discussion to two questions. Over the next four sessions, we finished within forty minutes instead of an hour. Attendance stayed stable. The sample was small, so I would track another month before drawing a firm conclusion.'}
  ],
  amazon: [
    {title: 'Start with the customer', tag: 'Customer Obsession', prompt: 'Tell me about a time customer feedback changed your plan. What trade-off did you make?', follow: 'How did you check that the change helped customers, not just your metrics?', hint: 'After listening to …, I changed … because …', sample: 'Students said our library booking form was confusing. I owned its redesign. I postponed a visual refresh to simplify the booking steps, then observed five students using it. All five completed a booking without assistance. I documented the small sample and scheduled another usability check.'},
    {title: 'Beyond your assignment', tag: 'Ownership', prompt: 'Describe a problem outside your assigned responsibilities that you took ownership of. What happened?', follow: 'How did you involve the owner and avoid creating a new long-term dependency?', hint: 'Although I was responsible for …, I noticed …', sample: 'While editing our club newsletter, I noticed broken event links. The website was not my assignment. I contacted its owner, offered to audit the links, and agreed on a handover. We repaired eight links before publication and added a pre-send checklist. The website owner kept responsibility for future checks.'},
    {title: 'Challenge, then commit', tag: 'Have Backbone; Disagree and Commit', prompt: 'Describe a time you respectfully challenged a decision but the team chose another direction. What did you do next?', follow: 'What would justify reopening that decision?', hint: 'I raised my concern about … Once we decided, I …', sample: 'I disagreed with running our open day outdoors because of the weather risk. I shared the forecast and suggested an indoor option. The team chose the courtyard. I committed to the plan, booked a backup room, and agreed on a rain threshold. We used the backup when it rained and kept the event on schedule.'}
  ]
};
// A brief original study note and original questions, not the ETS passage or official question set.
const readingNote = 'One explanation links dinosaur extinction to climate changes after seas retreated. Yet other cold-blooded animals survived, weakening that account. Unusually abundant iridium in boundary clay suggests an extraterrestrial source. An asteroid impact could have lifted dust into the atmosphere, reducing sunlight and disrupting photosynthesis.';
const readingQuestions = [
  {skill:'Evaluate evidence', prompt:'What weakens the climate explanation?', options:['All seas disappeared.','Other cold-blooded animals survived.','Iridium blocked the oceans.'], answer:1, why:'Surviving animals challenge the proposed explanation.'},
  {skill:'Identify a clue', prompt:'Which clue supports an extraterrestrial source?', options:['Unusually abundant iridium.','A growing dinosaur population.','Stable sea levels.'], answer:0, why:'The boundary clay contains an unusual concentration.'},
  {skill:'Trace a mechanism', prompt:'How could impact dust harm food production?', options:['By increasing sunlight.','By creating shallow seas.','By reducing light for photosynthesis.'], answer:2, why:'Less sunlight can disrupt photosynthesis.'}
];
const replies = [
  {line:'A little nervous, honestly. Want to practice together?', answer:'Of course. Let’s take the pressure off. Tell me about a time you helped your team.', reflection:'You named a feeling and made a clear invitation.', phrase:'Want to practice together?'},
  {line:'I’m still thinking about the reading. What did you make of it?', answer:'The evidence was the interesting part for me. Which clue did you find most convincing?', reflection:'You invited another perspective and kept the conversation open.', phrase:'What did you make of it?'},
  {line:'I need a little break. Shall we grab a tea first?', answer:'A tea sounds lovely. We can sit here for a while. What’s been the best part of your day?', reflection:'You expressed a need and suggested a shared activity.', phrase:'Shall we grab a tea first?'}
];
const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const icon = name => `<svg viewBox="0 0 24 24" aria-hidden="true">${({book:'<path d="M3 4h6a4 4 0 0 1 3 2 4 4 0 0 1 3-2h6v15h-6a4 4 0 0 0-3 2 4 4 0 0 0-3-2H3zM12 6v15"/>',arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',back:'<path d="M20 12H4m6-6-6 6 6 6"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1"/>',check:'<path d="m5 12 4 4L20 5"/>',chat:'<path d="M21 11a9 8 0 0 1-9 8H7l-4 3v-7a8 8 0 1 1 18-4Z"/>',leaf:'<path d="M20 3C4 1 1 12 7 17s15 0 13-14ZM4 21 16 8"/>'})[name] || '<circle cx="12" cy="12" r="8"/>'}</svg>`;
const link = (route, label, cls = 'btn') => `<a class="${cls}" href="#${route}">${label}</a>`;
const external = (url, label) => `<a href="${url}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`;
function save() { try {localStorage.setItem(KEY, JSON.stringify(state)); return true;} catch (_) {return false;} }
let toastTimer;
function toast(message) {const el=document.querySelector('.toast'); el.textContent=message; el.classList.add('show'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>el.classList.remove('show'),3000);}
function savedNotice() {toast(save() ? 'Saved on this device. Nothing was sent to a server.' : 'Kept for this visit only. Browser storage is unavailable.');}
function doneCount() {return Object.keys(state.reading).filter(k=>/^[0-2]$/.test(k)).length + Object.keys(state.reviewed).filter(k=>/^(google|amazon)-[0-2]$/.test(k)&&state.reviewed[k]).length + Number(!!state.friendDone);}
function pin(x,y,route,title,sub,type='book') {return `<a class="pin ${type==='chat'?'npc':'current'}" style="left:${x}%;top:${y}%" href="#${route}">${type==='chat'?'<span class="portrait-mini"></span>':`<span class="pin-icon">${icon(type)}</span>`}<span><b>${title}</b><small>${sub}</small></span><span class="enter-arrow">›</span></a>`;}
function campus() {
  return `<section class="campus" aria-label="Interactive campus map"><div class="world" id="world"><img src="assets/campus.png" alt="A warm cutaway campus: classroom, library, studio, and a leafy courtyard with students.">${pin(25,31,'classroom','Career classroom','6 stories · Google & Amazon')}${pin(77,33,'reading-room','Reading room','TOEFL · Dinosaurs')}${pin(21,65,'exercise','Language studio','A tiny conversation warm-up')}${pin(62,55,'friend','Maya','Free for a little chat','chat')}${pin(85,81,'friend','Courtyard café','Take a break with a friend','leaf')}</div><div class="welcome-note"><p class="eyebrow">YOUR LITTLE WORLD OF ENGLISH</p><h1>A little day at school.</h1><p>No rush. Pick a room.<br>Let your curiosity lead the way.</p></div><div class="weather">${icon('sun')}<span>09:28 <small>· 22°C · Early autumn</small></span></div><div class="map-tip">Drag to explore · Select a room or a friend</div><div class="map-control" aria-label="Map zoom"><button data-zoom="0.15" aria-label="Zoom in">+</button><button data-zoom="-0.15" aria-label="Zoom out">−</button><button data-zoom="reset" aria-label="Reset map view">⌖</button></div><div class="campus-dock"><div class="next-icon">${icon('book')}</div><div class="next-copy"><small>THE NEXT LITTLE STEP</small><strong>Turn experience into a story</strong></div><div class="day-progress"><p><span>Your demo journey</span><span>${doneCount()} / 10</span></p><div class="progress-line"><span style="width:${doneCount()*10}%"></span></div></div><span class="dock-divider"></span>${link('sources',`${icon('book')}<span>Sources</span>`,'dock-icon')}${link('classroom',`Go to class ${icon('arrow')}`)}</div></section>`;
}
function room(reading=false) {
  return `<section class="room-scene"><img class="scene-bg" src="assets/classroom.png" alt="Sunlit classroom with wooden desks, a green chalkboard and a teacher.">${link('campus',`${icon('back')} Back to campus`,'back scenic-back')}<div class="room-label"><span>${reading?'QUIET STUDY':'CAREER ENGLISH'}</span>${reading?'Reading seminar · Room 02':'Story workshop · Room 01'}</div><div class="board-label"><small>TODAY’S LITTLE PLAN</small><h2>${reading?'Follow the evidence.':'Every experience<br>has a story.'}</h2><p>${reading?'Read a study note<br>Find a clue · Check your reasoning':'Find your moment<br>Tell your story · Reflect & retry'}</p></div><div class="room-bottom"><div class="teacher-intro"><p class="eyebrow">MS. ELLIS · YOUR ENGLISH MENTOR</p><h1>${reading?'A question from another age.':'Come in. You have a story to tell.'}</h1><p>${reading?'“Today we’ll follow an argument, not just translate a paragraph. What makes one explanation convincing?”':'“You don’t need an extraordinary story. Start with something real, and help me understand your part in it.”'}</p></div><aside class="room-ticket"><p class="eyebrow">ON THE BLACKBOARD</p><h2>${reading?'Reading & reasoning':'The story workshop'}</h2><ul><li>${icon('check')} ${reading?'ETS public reading reference':'3 Google-guided prompts'}</li><li>${icon('check')} ${reading?'3 original comprehension questions':'3 Amazon principle scenarios'}</li><li>${icon('check')} ${reading?'Explanations after each answer':'A follow-up for every story'}</li></ul>${link(reading?'reading':'course',`Take a seat ${icon('arrow')}`,'btn full')}</aside></div></section>`;
}
function shell(content, active='course', title='The story workshop') {
  const links=[['course','The lesson'],['interviews','Story practice'],['reading','Reading room']];
  return `<div class="study-shell"><aside class="study-nav">${link('campus',`${icon('back')} Back to campus`,'back')}<div><small>YOUR ENGLISH NOTEBOOK</small><h2>${title}</h2></div><nav class="course-steps" aria-label="Learning activities">${links.map(([r,t],i)=>link(r,`<span>${i+1}</span>${t}`,active===r?'active':'')).join('')}</nav><div class="mentor-mini"><b>A note from Ms. Ellis</b><p>Small, honest details make a story yours. Give yourself room to try again.</p>${link('sources','Material & demo notes ↗','text-button')}</div></aside><section class="study-body view-enter"><div class="study-top"><span>ENGLISH, ONE LITTLE MOMENT AT A TIME</span><span>LOCAL PRACTICE</span></div>${content}</section></div>`;
}
function heading(eyebrow,title,description='') {return `<header class="study-heading"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1>${description?`<p>${description}</p>`:''}</header>`;}
function course() {
  return shell(`${heading('CAREER ENGLISH · GUIDED PRACTICE','Your experience.<br>A clearer story.','A small workshop in speaking about what you did, why it mattered, and what you would do differently.')}<div class="lesson-layout"><div><div class="plan">${[['01','Find a moment','Choose one of six real-world situations.','Choose'],['02','Build your story','Give context, your action, and an honest result.','Write'],['03','Go one layer deeper','Answer a follow-up. Then review your own story.','Reflect']].map(([n,t,d,m])=>`<div class="plan-row"><span class="plan-num">${n}</span><div><h3>${t}</h3><p>${d}</p></div><small>${m}</small></div>`).join('')}</div><div class="lesson-note"><strong>Two lenses, one notebook.</strong><br>Google-guided practice uses the current official preparation guide. Amazon-inspired practice connects stories to Leadership Principles. All six prompts are original adaptations, not official interview questions.</div></div><aside><div class="goal-card"><p class="eyebrow">TODAY’S INTENTION</p><h3>Be specific.<br>Be yourself.</h3><p>Use STAR as a guide, not a script. Your personal contribution should be easy to follow.</p><div class="mini-stats"><span><b>6</b>story prompts</span><span><b>1</b>follow-up each</span></div></div><div class="word-card"><p class="eyebrow">A USEFUL PHRASE</p><p class="word">Looking back, …</p><p>A natural way to introduce what you learned.</p><button data-action="translation">Show Chinese hint</button><p id="translation" hidden>回头来看……／现在回想起来……</p></div></aside></div><div class="study-actions">No recording. No automated proficiency score.${link('interviews',`Choose a story ${icon('arrow')}`)}</div>`);
}
function interviews(company='google') {
  return shell(`${heading('CAREER CLASSROOM · QUESTION LIBRARY','Which story will you tell?','Pick one prompt. Write a first attempt, answer a follow-up, and check the structure yourself.')}<div class="company-tabs" role="group" aria-label="Question collection">${link('interviews','Google-guided practice',company==='google'?'selected':'')}${link('amazon','Amazon principles',company==='amazon'?'selected':'')}</div><p class="source-caption">${company==='google'?'Adapted from Google’s preparation guidance · Page dated Dec 11, 2025.':'Original scenarios mapped to Amazon’s published Leadership Principles.'} ${external(sources[company],'Official source')}<br>Not an official interview question bank; no claim these questions were asked by either company.</p><div class="question-library">${questions[company].map((q,i)=>`<a href="#interview-${company}-${i}" class="question-card"><span class="question-number">0${i+1}</span><div><p class="eyebrow">${q.tag}</p><h2>${q.title}</h2><p>${q.prompt}</p><small>${state.reviewed[`${company}-${i}`]?'✓ Self-review completed':'Draft → follow-up → self-review'}</small></div><span class="question-arrow">↗</span></a>`).join('')}</div>`, 'interviews');
}
function interview(company,i,follow=false) {
  const q=questions[company][i], key=`${company}-${i}`, draft=state.drafts[key]||'', reply=state.followups[key]||'';
  return shell(`${link(company==='google'?'interviews':'amazon',`${icon('back')} All prompts`,'back')}<div class="interview-heading">${heading(`${company.toUpperCase()}-INSPIRED · ${q.tag} · ${i+1} / 3`,follow?'Let’s go one layer deeper.':q.title)}</div><div class="writing-layout"><div><p class="interview-prompt">${follow?q.follow:q.prompt}</p>${follow?`<details class="draft-preview"><summary>Your first response</summary><p>${escapeHTML(draft)||'No first response yet. Return to the prompt to draft one.'}</p></details>`:''}<label class="input-label" for="story">${follow?'Your follow-up':'Your story'} <span>Use a real experience. English is encouraged.</span></label><textarea id="story" class="story-input" maxlength="5000" placeholder="${follow?'Add one specific detail…':'Situation: …\nTask: …\nAction: …\nResult: …'}" data-company="${company}" data-index="${i}" data-follow="${follow}">${escapeHTML(follow?reply:draft)}</textarea><div class="writing-meta"><span id="word-count">${wordCount(follow?reply:draft)} words</span><span>Auto-saved locally · not sent to AI</span></div><div class="language-hint">Language starter · ${q.hint}</div>${!follow?`<details class="sample-answer"><summary>Read a fictional sample · do not copy as personal experience</summary><p>${q.sample}</p></details>`:''}<div class="study-actions">${link(follow?`interview-${key}`:(company==='google'?'interviews':'amazon'),follow?'Revise first response':'Choose another','back')}<button class="btn" data-submit-story="${key}" data-follow="${follow}" ${wordCount(follow?reply:draft)<5?'disabled':''}>${follow?'Review my story':'Save & see follow-up'} ${icon('arrow')}</button></div><p class="evidence-note">The follow-up is prewritten for this prompt, not generated from your answer.</p></div><aside class="star-card"><p class="eyebrow">YOUR STORY COMPASS</p>${[['S','Situation','Where were you?'],['T','Task','What was yours to solve?'],['A','Action','What did you do?'],['R','Result','What changed or did you learn?']].map(([l,t,d])=>`<div><span>${l}</span><p><b>${t}</b><small>${d}</small></p></div>`).join('')}<p class="evidence-note">Use accurate evidence. A small result is better than an invented number.</p></aside></div>`,'interviews');
}
function review(company,i) {
  const key=`${company}-${i}`, q=questions[company][i];
  const ready=wordCount(state.drafts[key]||'')>=5&&wordCount(state.followups[key]||'')>=5;
  return shell(`${heading('STORY NOTEBOOK · SELF-REVIEW','A story worth refining.','This is a self-check, not an AI evaluation or a hiring recommendation.')}<p class="pill">${q.tag}</p><div class="result-pair"><div><p class="eyebrow">YOUR FIRST RESPONSE</p><p class="user-copy">${escapeHTML(state.drafts[key]||'Write your first response to begin.')}</p></div><div><p class="eyebrow">THE FOLLOW-UP</p><p>${q.follow}</p><p class="user-copy">${escapeHTML(state.followups[key]||'Add a follow-up response before completing the activity.')}</p></div></div><h2>Read it once. What is clear?</h2><div class="self-checks">${['I gave enough context without a long introduction.','I made my own responsibility and actions clear.','I used an accurate result, or an honest lesson.','I answered the follow-up with a specific detail.'].map((t,n)=>`<label><input type="checkbox" name="review-check" value="${n}"> ${t}</label>`).join('')}</div><p class="evidence-note">These checks are for your reflection. Completing the activity does not mean your answer is correct.</p><div class="study-actions">${link(`interview-${key}`,'Revise my story','back')}<button class="btn" data-complete-story="${key}" ${ready?'':'disabled'}>Finish self-review ${icon('check')}</button></div>${!ready?'<p class="evidence-note">Please write both responses first (at least five words each).</p>':''}`,'interviews');
}
function reading(index=0,finished=false) {
  if(finished) {
    const attempted=readingQuestions.filter((q,i)=>Number.isInteger(state.reading[i])).length;
    const score=readingQuestions.filter((q,i)=>state.reading[i]===q.answer).length;
    return shell(`${heading('READING ROOM · PRACTICE SUMMARY',attempted===3?'A little more clarity.':'Your reading notebook.','This score describes only the three original questions in this demo. It is not a TOEFL score.')}<div class="reading-score">${score}<span>/ 3 correct · ${attempted} answered</span></div>${readingQuestions.map((q,i)=>`<div class="memory-item"><span>${i+1}. ${q.skill}</span><b>${!Number.isInteger(state.reading[i])?'Not answered':state.reading[i]===q.answer?'Correct':'Review needed'}</b></div>`).join('')}<div class="study-actions"><button class="btn secondary" data-action="retry-reading">Try again</button>${link('friend',`Tell Maya about your day ${icon('arrow')}`)}</div><p class="evidence-note">${external(sources.ets,'Read the full ETS passage')} · Reading Practice Set 2, pages 8–9.</p>`,'reading','The reading room');
  }
  const q=readingQuestions[index], submitted=Number.isInteger(state.reading[index]), choice=state.reading[index];
  return shell(`${heading('TOEFL READING REFERENCE · SCIENCE','Extinction of the Dinosaurs','A short evidence-reading activity based on an ETS public practice passage.')}<div class="reading-source"><span>ETS · 2023 practice material</span>${external(sources.ets,'Open full official passage')}</div><p class="source-caption">Original condensed study note and original questions below. This is not the full ETS text or a simulation of the current TOEFL exam.</p><div class="reading-layout"><article class="reading-paper"><p class="eyebrow">THE STUDY NOTE</p><h2>Following the clues</h2><p>${readingNote}</p><span class="paper-footnote">Read slowly. Separate an explanation from evidence.</span></article><section class="reading-question"><p class="eyebrow">QUESTION ${index+1} OF 3 · ${q.skill}</p><h2>${q.prompt}</h2><div class="answers">${q.options.map((o,n)=>`<button class="answer ${submitted?(n===q.answer?'correct':n===choice?'incorrect':''):''}" data-reading-choice="${n}" aria-pressed="${submitted&&n===choice}" ${submitted?'disabled':''}><span>${String.fromCharCode(65+n)}</span>${o}</button>`).join('')}</div>${submitted?`<div class="inline-feedback ${choice===q.answer?'':'retry'}" role="status"><b>${choice===q.answer?'Correct.':'Not quite.'}</b> ${q.why}</div>`:''}<div class="exercise-controls"><p>${submitted?'Answer checked':'Select one answer'}</p>${submitted?link(index===2?'reading-result':`reading-${index+1}`,` ${index===2?'See summary':'Next question'} ${icon('arrow')}`):`<button class="btn" id="check-reading" data-index="${index}" disabled>Check answer</button>`}</div></section></div><div class="reading-pager" aria-label="Reading question navigation">${readingQuestions.map((_,n)=>link(`reading-${n}`,`${n+1}`,n===index?'selected':'')).join('')}</div>`,'reading','The reading room');
}
function warmup(feedback=false) {
  return shell(`${heading('LANGUAGE STUDIO · A SMALL WARM-UP',feedback?'A softer way to connect.':'Leave room for a reply.','Maya looks a little nervous before her interview practice. What would help the conversation continue?')}${feedback?`<div class="result-pair"><div><p class="eyebrow">A USEFUL RESPONSE</p><blockquote>“Want to practice together?”</blockquote></div><div><p class="eyebrow">WHY IT HELPS</p><p>An invitation offers support without assuming how the other person feels.</p></div></div>${link('friend',`Try a conversation ${icon('arrow')}`)}`:`<div class="exercise-card"><p class="quote">“I’m not sure I can explain my experience very well.”</p><div class="answers">${['You should have prepared more.','Want to practice together?','Anyway, I’m ready for mine.'].map((t,i)=>`<button class="answer" data-warmup="${i}"><span>${String.fromCharCode(65+i)}</span>${t}</button>`).join('')}</div><div id="warmup-response" aria-live="polite"></div></div>`}`);
}
function social(next=false) {
  const r=replies[state.friendChoice]||replies[0];
  return `<section class="social-scene"><img class="scene-bg" src="assets/courtyard.png" alt="Two adult students talking beside a bench in an autumn campus courtyard.">${link('campus',`${icon('back')} Back to campus`,'back scenic-back')}<div class="scene-navigator">COURTYARD · BETWEEN CLASSES</div><div class="relationship"><p class="eyebrow">SOMEONE YOU KNOW</p><strong>Maya</strong><small>Your classmate</small></div><div class="dialogue-box"><div class="speaker"><b>Maya</b><small>${next?'02 / A LITTLE DEEPER':'01 / SAY HELLO'}</small></div>${next?`<p class="your-line">You · ${r.line}</p>`:''}<p class="spoken">${next?r.answer:'Hey, there you are! I saved you a spot. How’s your day going?'}</p>${next?`<label class="input-label" for="friend-reply">Your reply <span>A sentence or two is enough.</span></label><div class="compose"><textarea id="friend-reply" maxlength="1200" placeholder="I’d say…">${escapeHTML(state.friendReply)}</textarea><button class="btn" id="send-friend" ${String(state.friendReply||'').trim().length<3?'disabled':''}>Reply ${icon('arrow')}</button></div><div class="language-hint">Try starting with: “What I found interesting was…” or “One thing I learned today…”</div><p class="conversation-note">This demo shows a scripted acknowledgment, not AI language feedback.</p>`:`<div class="response-grid">${replies.map((r,i)=>`<button class="response-choice" data-friend="${i}"><span>0${i+1}</span>${r.line}</button>`).join('')}</div><p class="conversation-note">Choose what feels like you. Each response opens a different conversation.</p>`}</div></section>`;
}
function reflection() {
  const r=replies[state.friendChoice]||replies[0];
  return shell(`${heading('CAMPUS LIFE · A MOMENT WITH MAYA',state.friendDone?'A small conversation.<br>A little connection.':'Your conversation notebook.','There is no friendship score to chase. Just another opportunity to use your English.')}<div class="result-pair"><div><p class="eyebrow">YOU SAID</p><blockquote>${escapeHTML(state.friendReply)||'Say hello to Maya to start a conversation.'}</blockquote></div><div><p class="eyebrow">MAYA · SCRIPTED ACKNOWLEDGMENT</p><blockquote>${state.friendDone?'“Thanks for sharing that with me. Shall we walk to the next class together?”':'“I saved you a spot.”'}</blockquote></div></div><div class="goal-card"><p class="eyebrow">A PHRASE TO KEEP</p><h3>${r.phrase}</h3><p>${r.reflection}</p></div><p class="evidence-note">The reflection describes your selected conversation opener, not the quality of your typed English. ${state.friendDone?'Your reply is kept locally when browser storage is available.':''}</p><div class="study-actions">${link('friend','Try another opener','back')}${link('campus',`Back to our little world ${icon('arrow')}`)}</div>`,'course','Campus conversations');
}
function sourcePage() {
  return shell(`${heading('THE MATERIAL BEHIND THE DEMO','Real references.<br>Honest boundaries.','Sources checked on September 9, 2026. This independent concept is not affiliated with ETS, Google, or Amazon.')}<div class="source-list"><article><p class="eyebrow">01 · PUBLIC READING MATERIAL</p><h2>ETS · Reading Practice Set 2</h2><p>Selected passage: <i>Extinction of the Dinosaurs</i>, pages 8–9. The PDF is © 2023 ETS and identifies the 2023 test format. The demo uses a short original study note and three original questions; it does not reproduce the passage or represent the 2026 test format.</p>${external(sources.ets,'ETS official PDF')}</article><article><p class="eyebrow">02 · INTERVIEW PREPARATION</p><h2>Grow with Google</h2><p><i>How to prepare for an interview</i>, dated December 11, 2025. The page recommends STAR and concrete evidence. Our three practice prompts are adaptations of the guidance, not three newly released Google interview questions. No newer publication date was established in this research.</p>${external(sources.google,'Current Google official guide')}</article><article><p class="eyebrow">03 · LEADERSHIP PRINCIPLES</p><h2>Amazon Jobs</h2><p>Three original scenarios map to Customer Obsession, Ownership, and Have Backbone; Disagree and Commit. The official interview-loop page also explains behavioral preparation and STAR. No official question-bank status is claimed.</p>${external(sources.amazon,'Official principles')} · ${external(sources.star,'Official interview preparation')}</article><article><p class="eyebrow">04 · PROTOTYPE, NOT A LIVE AGENT</p><h2>A connected visual prototype</h2><p>The three campus illustrations were AI-generated for this demo. Scenic navigation leads to quiet learning pages. Answers and progress stay in this browser, when storage is available. No account, microphone, recording, AI generation, automatic writing score, or external submission is connected. Fictional sample stories are labeled.</p><p>Full lessons, conversation memory, pronunciation assessment, and real movement/pathfinding are later product work. Map panning and hotspots are implemented here.</p></article></div>${link('campus','Back to campus')}`);
}
function wordCount(text) {return String(text||'').trim().split(/\s+/).filter(Boolean).length;}
function render() {
  let route=location.hash.slice(1)||'campus';
  if(route==='main') {main.focus(); return;}
  let match;
  if((match=route.match(/^(interview|followup|review)-(google|amazon)-([0-2])$/))) main.innerHTML=match[1]==='review'?review(match[2],Number(match[3])):interview(match[2],Number(match[3]),match[1]==='followup');
  else if((match=route.match(/^reading-([0-2])$/))) main.innerHTML=reading(Number(match[1]));
  else main.innerHTML=({'campus':campus,'classroom':()=>room(),'reading-room':()=>room(true),'course':course,'interviews':()=>interviews(),'amazon':()=>interviews('amazon'),'reading':()=>reading(),'reading-result':()=>reading(0,true),'exercise':()=>warmup(),'feedback':()=>warmup(true),'friend':()=>social(),'conversation':()=>social(true),'reflection':reflection,'sources':sourcePage}[route]||campus)();
  main.dataset.route=route;
  document.querySelector('#scenes-dialog').close();
  window.scrollTo(0,0);
  main.focus({preventScroll:true});
  if(route==='campus'||!location.hash) bindMap();
}
function bindMap() {
  const world=document.querySelector('#world'); if(!world)return;
  const map=world.parentElement; let zoom=1, x=0,y=0, drag=null, moved=false;
  const update=()=> {const maxX=Math.max(0,(world.offsetWidth*zoom-map.clientWidth)/2), maxY=Math.max(0,(world.offsetHeight*zoom-map.clientHeight)/2); x=Math.max(-maxX,Math.min(maxX,x)); y=Math.max(-maxY,Math.min(maxY,y)); world.style.transform=`translate(calc(-50% + ${x}px),calc(-50% + ${y}px)) scale(${zoom})`;};
  document.querySelectorAll('[data-zoom]').forEach(b=>b.onclick=()=>{if(b.dataset.zoom==='reset'){zoom=1;x=0;y=0;}else zoom=Math.max(.85,Math.min(1.6,zoom+Number(b.dataset.zoom)));update();});
  world.addEventListener('pointerdown',e=>{if(e.button!==0)return;drag={x:e.clientX,y:e.clientY,startX:x,startY:y};moved=false;});
  world.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>5){moved=true;world.setPointerCapture(e.pointerId);world.style.transition='none';}x=drag.startX+dx;y=drag.startY+dy;update();});
  const end=()=>{drag=null;world.style.transition='';};
  world.addEventListener('pointerup',end);world.addEventListener('pointercancel',end);world.addEventListener('lostpointercapture',end);
  world.addEventListener('click',e=>{if(moved){e.preventDefault();e.stopPropagation();moved=false;}},true);
}
main.addEventListener('click',e=>{
  const target=e.target.closest('button'); if(!target || target.disabled)return;
  if(target.dataset.action==='translation') {const p=document.querySelector('#translation');p.hidden=!p.hidden;target.textContent=p.hidden?'Show Chinese hint':'Hide Chinese hint';}
  if(target.dataset.action==='retry-reading'){state.reading={};save();location.hash='reading';}
  if(target.dataset.readingChoice!==undefined){document.querySelectorAll('[data-reading-choice]').forEach(b=>{b.classList.toggle('selected',b===target);b.setAttribute('aria-pressed',String(b===target));});const check=document.querySelector('#check-reading');check.disabled=false;check.dataset.choice=target.dataset.readingChoice;}
  if(target.id==='check-reading'){state.reading[target.dataset.index]=Number(target.dataset.choice);save();render();}
  if(target.dataset.warmup!==undefined){document.querySelectorAll('[data-warmup]').forEach(b=>b.classList.toggle('selected',b===target));document.querySelector('#warmup-response').innerHTML=target.dataset.warmup==='1'?`<div class="inline-feedback">An invitation gives Maya a choice.</div>${link('feedback','Continue →')}`:'<div class="inline-feedback retry">Try a response that offers support and leaves room for a reply.</div>';if(target.dataset.warmup==='1'){state.warmup=true;save();}}
  if(target.dataset.friend!==undefined){state.friendChoice=Number(target.dataset.friend);state.friendReply='';state.friendDone=false;save();location.hash='conversation';}
  if(target.id==='send-friend'){state.friendReply=document.querySelector('#friend-reply').value.trim();if(state.friendReply.length<3)return;state.friendDone=true;save();location.hash='reflection';}
  if(target.dataset.submitStory){const key=target.dataset.submitStory,following=target.dataset.follow==='true',text=document.querySelector('#story').value.trim();if(wordCount(text)<5)return;(following?state.followups:state.drafts)[key]=text;save();location.hash=`${following?'review':'followup'}-${key}`;}
  if(target.dataset.completeStory){const checked=document.querySelectorAll('[name="review-check"]:checked').length;if(!checked){toast('Select at least one statement you can honestly confirm, or revise your story.');return;}state.reviewed[target.dataset.completeStory]=true;savedNotice();location.hash=target.dataset.completeStory.startsWith('amazon')?'amazon':'interviews';}
});
main.addEventListener('input',e=>{
  const el=e.target;
  if(el.id==='story'){const key=`${el.dataset.company}-${el.dataset.index}`;(el.dataset.follow==='true'?state.followups:state.drafts)[key]=el.value;state.reviewed[key]=false;const persisted=save();document.querySelector('#word-count').textContent=`${wordCount(el.value)} words`;document.querySelector('.writing-meta span:last-child').textContent=persisted?'Auto-saved locally · not sent to AI':'Session only · browser storage unavailable';document.querySelector('[data-submit-story]').disabled=wordCount(el.value)<5;}
  if(el.id==='friend-reply'){state.friendReply=el.value;save();document.querySelector('#send-friend').disabled=el.value.trim().length<3;}
});
document.querySelector('#scene-index').onclick=()=>document.querySelector('#scenes-dialog').showModal();
document.querySelector('[data-close]').onclick=()=>document.querySelector('#scenes-dialog').close();
document.querySelector('#scenes-dialog').addEventListener('click',e=>{if(e.target.closest('a'))document.querySelector('#scenes-dialog').close();});
document.querySelector('#reset').onclick=()=>{if(!confirm('Delete this demo’s saved responses and progress on this device?'))return;state=initial();try{localStorage.removeItem(KEY);}catch(_){}document.querySelector('#scenes-dialog').close();if(location.hash==='#campus')render();else location.hash='campus';toast('This demo’s local progress has been reset.');};
window.addEventListener('hashchange',render);
render();
